-- copied and adapted code from switchfully-jpa-solution-order

-- following code is to be executed to create the proper user (local)
--CREATE USER SHARK IDENTIFIED BY "SHARK";
--GRANT CREATE SESSION TO SHARK;
--GRANT CREATE TABLE TO SHARK;
--ALTER DATABASE DEFAULT TABLESPACE users;
--GRANT UNLIMITED TABLESPACE TO SHARK;
--grant CREATE SEQUENCE to SHARK;

-- DIVISIONS
DROP TABLE DIVISIONS;
CREATE TABLE DIVISIONS
  (
    ID                 VARCHAR2(100) NOT NULL,
    NAME               VARCHAR2(100) NOT NULL,
    ORIGINAL_NAME      VARCHAR2(100) NOT NULL,
    DIRECTOR           VARCHAR2(100) NOT NULL,
    PARENT_DIVISION_ID VARCHAR2(100),
    CONSTRAINT DIVISIONS_PK PRIMARY KEY (ID),
    --https://www.techonthenet.com/oracle/unique.php
    CONSTRAINT DIVISIONS_NAME_UNIQUE UNIQUE (NAME)
  );

----CONTACT_PERSONS
--DROP TABLE CONTACT_PERSONS;
--CREATE TABLE CONTACT_PERSONS
--  (
--    ID                  VARCHAR2(100) NOT NULL,
--    NAME                VARCHAR2(100) NOT NULL,
--    TELEPHONE_NUMBER    VARCHAR2(100) NOT NULL,
--    MOBILE_PHONE_NUMBER VARCHAR2(100) NOT NULL,
--    EMAIL               VARCHAR2(100) NOT NULL,
--    STREET_NAME         VARCHAR2(100) NOT NULL,
--    STREET_NUMBER       VARCHAR2(100) NOT NULL,
--    POSTALCODE          VARCHAR2(100) NOT NULL,
--    LABEL               VARCHAR2(100) NOT NULL,
--    CONSTRAINT CONTACT_PERSONS_PK PRIMARY KEY (ID)
--  );

----PARKINGLOTS
--DROP TABLE PARKINGLOTS;
--CREATE TABLE PARKINGLOTS
--  (
--    ID                     VARCHAR2(100) NOT NULL,
--    NAME                   VARCHAR2(100) NOT NULL,
--    DIVISION_ID            VARCHAR2(100) NOT NULL,
--    CAPACITY               INT NOT NULL,
--    PRICE_PER_HOUR_IN_EURO DECIMAL(5,2) NOT NULL,
--    CONTACT_PERSON_ID      VARCHAR2(100) NOT NULL,
--    BULDING_TYPE           VARCHAR2(100) NOT NULL,
--    STREET_NAME            VARCHAR2(100) NOT NULL,
--    STREET_NUMBER          VARCHAR2(100) NOT NULL,
--    POSTALCODE             VARCHAR2(100) NOT NULL,
--    LABEL                  VARCHAR2(100) NOT NULL,
--    CONSTRAINT PARKINGLOTS_PK PRIMARY KEY (ID),
--    CONSTRAINT FK_DIVISION_ID FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(ID),
--    CONSTRAINT FK_CONTACT_PERSON_ID FOREIGN KEY (CONTACT_PERSON_ID) REFERENCES CONTACT_PERSONS(ID)
--  );

---- PHONE_NUMBERS
--DROP TABLE PHONE_NUMBERS;
--CREATE TABLE PHONE_NUMBERS
--  (
--    ID                  VARCHAR2(100) NOT NULL,
--    TELEPHONE_NUMBER    VARCHAR2(100) NOT NULL,
--    MOBILE_PHONE_NUMBER VARCHAR2(100) NOT NULL,
--    CONSTRAINT PHONE_NUMBERS_PK PRIMARY KEY (ID)
--  );